### ISSUE TITLE
Make double-tap for sprinting/flying work more like RandomPatches

### ISSUE THREAD

**Issue by muzikbike** [Minenash/RebindAllTheKeys#53]
Kind of hard to describe, but it goes like this:

- By default, the fly keybind would be bound to Space, just like the jump key is
- When both are bound to the same key, pressing it once would jump and pressing it twice would initiate flying, just like in vanilla
- When bound to separate keys, one key would be used for jumping and the other for flying, and there would be no special double-tap functionality

The same would go for sprinting - there would be a new dedicated "secondary sprint" keybind that would be bound to the forward key by default, and would work identically to the other sprint keybind.

Since we could then rebind (or unbind) these keys, there would no longer be any need for the "Double Tap Sprint" and "Double Tap Fly" buttons, and they could therefore be removed.

**Comment by Minenash** [comment]
Hm, I understand the idea, but I think this kind of behavior would be more confusing to convey to players rather than the current one. The thing that would be added here is the ability to have the "tap to do X, hold to do Y" be on keys other than the forward and jump key. I'm just not sure if that is worth removing the straight-forwardness of the current options
